-- 1. Criação do Banco de Dados
CREATE DATABASE IF NOT EXISTS PinguinismoDB;
USE PinguinismoDB;

-- 2. Tabela de Cadastro para Autistas / Familiares
CREATE TABLE IF NOT EXISTS TBL_CADASTRO_AUTISTA (
    ID_AUTISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_COMPLETO VARCHAR(100) NOT NULL,
    CPF_MASCARADO VARCHAR(14) NOT NULL,
    IDADE INT NOT NULL,
    CARTEIRA_CIPTEA VARCHAR(50) NOT NULL UNIQUE,
    NOME_USUARIO VARCHAR(30) NOT NULL UNIQUE,
    SENHA_ACESSO VARCHAR(255) NOT NULL
);

-- 3. Tabela de Cadastro para Especialistas de Saúde
CREATE TABLE IF NOT EXISTS TBL_CADASTRO_ESPECIALISTA (
    ID_ESPECIALISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_COMPLETO VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    IDENTIDADE_PROFISSIONAL VARCHAR(30) NOT NULL UNIQUE,
    NOME_USUARIO_PROFISSIONAL VARCHAR(50) NOT NULL UNIQUE,
    SENHA_ACESSO VARCHAR(255) NOT NULL
);